### ISSUE TITLE
Add tab with a list of running Service Workers and notifications originated from them 

### ISSUE THREAD

**Issue by KlausEverWalkingDev** [jingyu9575/service-worker-control#4]
Every now and then I meet so very weird and unsolicited notifications clearly coming from page I allowed to show notifications. I discovered today that I can use the Whose Your Daddy (https://addons.mozilla.org/en-US/firefox/addon/whose-your-daddy) to know their origin. But I would like to have a page/tab with all related with those Service Workers. Just this I'll not have a bank notification coming from tech webpages...

**Comment by jingyu9575** [comment]
I'd say this is not simple to implement. The only way I can think of is to modify all the service worker scripts to log notifications to my extension, but it will only work on newly registered service workers. I can also force websites to re-register the scripts but it requires opening the websites. Therefore, at least you will need to reopen all the relevent sites once to be able to log the notifications.

Do you still want this feature?

**Comment by KlausEverWalkingDev** [comment]
Thanks for the great explanation (I'm very noobie) and for your reply. Like I said, it annoys me when I check to some page's notifications (that I'm sure I want to receive, often based on my topics preferences) and any of those pages uses the Service Worker service to deliver advertisement (I'm define this as a abuse, let alone they are probably being paid for that). But to know the origin of notification I have to click it in the time it appears. After that, they are gone. My idea is have a place to allow us to decide (and investigate after) if we want that kind of notification or not. It could be in the extension button's popup, but I think it will be "neatier" if we could see it in a tab.

**Comment by jingyu9575** [comment]
Notification history is added to v1. As noted in the previous comment, this only works for newly registered service workers after it is enabled. 

I haven't test it, but according to documentations, when opening websites with existing service workers, they may be updated if they are >24h old. If this is true, simply opening the website will enable the notification history feature for it; otherwise, you may need to manually remove the service workers from each website.
